name: Schedule Netlify Build
on:
  schedule:
    - cron: "45 1-20/6 * * *"
jobs:
  build:
    name: Call Netlify build hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILDHOOK }}