name: Schedule Netlify Build
on:
  schedule:
    - cron: "30 15 * * *"
jobs:
  build:
    name: Call Netlify build hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/65bfa0203c6c596797c6569a